-- 1️⃣ Total Revenue
-- This query calculates the total revenue generated by the e-commerce
-- It sums all order values from the orders table

SELECT 
SUM(total_amount) AS total_revenue
FROM orders;

-- 2️⃣ Monthly Revenue
-- This query calculates total revenue per month
-- DATE_FORMAT extracts the year and month from the order_date
-- GROUP BY groups the results by each month

SELECT 
DATE_FORMAT(order_date, '%Y-%m') AS month,
SUM(total_amount) AS revenue
FROM orders
GROUP BY month
ORDER BY month;

-- 3️⃣ Average Order Value (Average Ticket)
-- This query calculates the average order value (average ticket)
-- AVG computes the average of all order totals
-- ROUND limits the result to 2 decimal places

SELECT 
ROUND(AVG(total_amount),2) AS avg_ticket
FROM orders;

-- 4️⃣ Top 10 Best-Selling Products
-- This query identifies the top 10 most sold products
-- It joins order_items with products to get product names
-- SUM(quantity) calculates the total number of units sold per product

SELECT 
p.product_name,
SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN products p 
ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_sold DESC
LIMIT 10;

-- 5️⃣ Top 10 Customers by Revenue
-- This query finds the top 10 customers who spent the most money
-- It joins customers with orders
-- SUM(total_amount) calculates total spending per customer

SELECT 
c.name,
SUM(o.total_amount) AS total_spent
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.name
ORDER BY total_spent DESC
LIMIT 10;

-- 6️⃣ Customers at Risk (Churn Analysis)
-- This query identifies customers who haven't made a purchase in the last 90 days
-- MAX(order_date) finds the most recent purchase for each customer
-- DATE_SUB compares the last purchase date with today's date

SELECT 
c.name,
MAX(o.order_date) AS last_purchase
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_id
HAVING last_purchase < DATE_SUB(CURDATE(), INTERVAL 90 DAY);

-- 7️⃣ Revenue by Product Category
-- This query calculates revenue generated by each product category
-- It joins order_items with products
-- Revenue is calculated by multiplying quantity by price

SELECT 
p.category,
SUM(oi.quantity * oi.price) AS revenue
FROM order_items oi
JOIN products p 
ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue DESC;
